from __future__ import annotations

import subprocess
import tempfile
import unittest
from pathlib import Path

from git_tools.generators.bumpgen import decide_version_strategy


class GitFlowStrategyTests(unittest.TestCase):
    def _git(self, root: Path, *args: str) -> str:
        result = subprocess.run(
            ["git", *args],
            cwd=root,
            check=True,
            text=True,
            capture_output=True,
        )
        return result.stdout.strip()

    def _init_repo(self, root: Path, version: str, *, message: str = "chore: init") -> None:
        self._git(root, "init")
        self._git(root, "branch", "-M", "master")
        self._git(root, "config", "user.name", "Test User")
        self._git(root, "config", "user.email", "test@example.com")
        self._git(root, "config", "commit.gpgSign", "false")
        self._git(root, "config", "tag.gpgSign", "false")
        self._write_version_files(root, version)
        self._commit_all(root, message)

    def _write_version_files(self, root: Path, version: str) -> None:
        (root / ".cz.toml").write_text(
            (
                "[tool.commitizen]\n"
                'name = "cz_conventional_commits"\n'
                'tag_format = "$version"\n'
                'version_scheme = "semver2"\n'
                f'version = "{version}"\n'
            ),
            encoding="utf-8",
        )
        (root / "pyproject.toml").write_text(
            (
                "[project]\n"
                'name = "example-project"\n'
                f'version = "{version}"\n'
            ),
            encoding="utf-8",
        )

    def _commit_all(self, root: Path, message: str) -> None:
        self._git(root, "add", ".")
        self._git(root, "commit", "-m", message)

    def _set_version(self, root: Path, version: str, *, message: str) -> None:
        self._write_version_files(root, version)
        self._commit_all(root, message)

    def _commit_empty(self, root: Path, subject: str, *, body: str | None = None) -> None:
        args = ["commit", "--allow-empty", "-m", subject]
        if body is not None:
            args.extend(["-m", body])
        self._git(root, *args)

    def test_variant_release_branch_cut_does_not_start_rc_without_unique_commit(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "0.1.0")
            self._git(root, "tag", "0.1.0")
            self._git(root, "checkout", "-b", "develop")
            self._set_version(
                root,
                "0.2.0-alpha.1",
                message="bump: version 0.1.0 -> 0.2.0-alpha.1",
            )
            self._git(root, "checkout", "-b", "release/1.0.0")

            decision = decide_version_strategy(root, "release/1.0.0", flow="variant")

            self.assertTrue(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "")
            self.assertEqual(decision.reason, "release branch has no unique human commit yet")
            self.assertEqual(decision.branch_gate_ref, "develop")
            self.assertFalse(decision.branch_has_unique_commits)

    def test_develop_skips_dvc_experiment_commit(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "0.2.0-alpha.0")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "dvc: commit experiment 7cef9647b1cb8f94")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertTrue(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "")
            self.assertEqual(
                decision.reason,
                "latest commit was generated by DVC experiment tracking",
            )
            self.assertFalse(decision.bump_eligible)

    def test_variant_release_branch_starts_rc_after_unique_human_commit(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "0.1.0")
            self._git(root, "tag", "0.1.0")
            self._git(root, "checkout", "-b", "develop")
            self._set_version(
                root,
                "0.2.0-alpha.1",
                message="bump: version 0.1.0 -> 0.2.0-alpha.1",
            )
            self._git(root, "checkout", "-b", "release/1.0.0")
            (root / "qa.txt").write_text("stabilize release\n", encoding="utf-8")
            self._commit_all(root, "fix: stabilize release branch")

            decision = decide_version_strategy(root, "release/1.0.0", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "start-release-rc")
            self.assertEqual(
                decision.args,
                "--yes --increment MAJOR --prerelease rc --increment-mode exact --gpg-sign",
            )
            self.assertTrue(decision.branch_has_unique_commits)
            self.assertEqual(decision.branch_gate_ref, "develop")

    def test_variant_release_opener_commit_can_start_rc(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "0.1.0")
            self._git(root, "tag", "0.1.0")
            self._git(root, "checkout", "-b", "develop")
            self._set_version(
                root,
                "0.2.0-alpha.1",
                message="bump: version 0.1.0 -> 0.2.0-alpha.1",
            )
            self._git(root, "checkout", "-b", "release/1.0.0")
            self._commit_empty(root, "chore: open release")

            decision = decide_version_strategy(root, "release/1.0.0", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "start-release-rc")
            self.assertEqual(
                decision.args,
                "--yes --increment MAJOR --prerelease rc --increment-mode exact --gpg-sign",
            )

    def test_variant_release_opener_with_github_pr_suffix_can_start_rc(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "0.1.0")
            self._git(root, "tag", "0.1.0")
            self._git(root, "checkout", "-b", "develop")
            self._set_version(
                root,
                "0.2.0-alpha.1",
                message="bump: version 0.1.0 -> 0.2.0-alpha.1",
            )
            self._git(root, "checkout", "-b", "release/1.0.0")
            self._commit_empty(root, "chore: open release (#9)")

            decision = decide_version_strategy(root, "release/1.0.0", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "start-release-rc")
            self.assertEqual(
                decision.args,
                "--yes --increment MAJOR --prerelease rc --increment-mode exact --gpg-sign",
            )

    def test_variant_release_branch_uses_exact_mode_for_target_line_jump(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.0.0")
            self._git(root, "tag", "1.0.0")
            self._git(root, "checkout", "-b", "develop")
            self._set_version(
                root,
                "1.0.0-alpha.3",
                message="bump: version 1.0.0 -> 1.0.0-alpha.3",
            )
            self._git(root, "checkout", "-b", "release/1.1.0")
            (root / "qa.txt").write_text("stabilize release\n", encoding="utf-8")
            self._commit_all(root, "fix: stabilize release branch")

            decision = decide_version_strategy(root, "release/1.1.0", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "start-release-rc")
            self.assertEqual(
                decision.args,
                "--yes --increment MINOR --prerelease rc --increment-mode exact --gpg-sign",
            )

    def test_hotfix_branch_cut_does_not_start_rc_without_unique_commit(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.0.0", message="fix: production stabilization")
            self._git(root, "tag", "1.0.0")
            self._git(root, "checkout", "-b", "hotfix/session-timeout")

            decision = decide_version_strategy(root, "hotfix/session-timeout", flow="variant")

            self.assertTrue(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "")
            self.assertEqual(decision.reason, "hotfix branch has no unique human commit yet")
            self.assertEqual(decision.branch_gate_ref, "master")
            self.assertFalse(decision.branch_has_unique_commits)

    def test_hotfix_branch_starts_rc_after_unique_human_commit(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.0.0", message="fix: production stabilization")
            self._git(root, "tag", "1.0.0")
            self._git(root, "checkout", "-b", "hotfix/session-timeout")
            (root / "timeout.txt").write_text("increase timeout threshold\n", encoding="utf-8")
            self._commit_all(root, "fix: repair session timeout handling")

            decision = decide_version_strategy(root, "hotfix/session-timeout", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "start-hotfix-rc")
            self.assertEqual(
                decision.args,
                "--yes --increment PATCH --prerelease rc --gpg-sign",
            )
            self.assertEqual(decision.hotfix_target, "1.0.1")
            self.assertTrue(decision.branch_has_unique_commits)
            self.assertEqual(decision.branch_gate_ref, "master")

    def test_master_can_finalize_prerelease_even_when_latest_commit_is_generated(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(
                root,
                "1.0.0-rc.2",
                message="bump: version 1.0.0-rc.1 -> 1.0.0-rc.2",
            )

            decision = decide_version_strategy(root, "master", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "finalize-stable")
            self.assertEqual(decision.args, "--yes --gpg-sign")

    def test_classic_release_branch_cut_does_not_promote_alpha_without_unique_commit(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.5.0")
            self._git(root, "tag", "1.5.0")
            self._git(root, "checkout", "-b", "develop")
            self._set_version(
                root,
                "1.6.0-alpha.0",
                message="bump: version 1.5.0 -> 1.6.0-alpha.0",
            )
            self._git(root, "checkout", "-b", "release/1.6.0")

            decision = decide_version_strategy(root, "release/1.6.0", flow="classic")

            self.assertTrue(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "")
            self.assertEqual(decision.reason, "release branch has no unique human commit yet")
            self.assertFalse(decision.branch_has_unique_commits)

    def test_classic_release_branch_promotes_alpha_after_unique_human_commit(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.5.0")
            self._git(root, "tag", "1.5.0")
            self._git(root, "checkout", "-b", "develop")
            self._set_version(
                root,
                "1.6.0-alpha.0",
                message="bump: version 1.5.0 -> 1.6.0-alpha.0",
            )
            self._git(root, "checkout", "-b", "release/1.6.0")
            (root / "release.txt").write_text("release validation fix\n", encoding="utf-8")
            self._commit_all(root, "fix: address release validation")

            decision = decide_version_strategy(root, "release/1.6.0", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "promote-alpha-to-rc")
            self.assertEqual(
                decision.args,
                "--yes --increment PATCH --prerelease rc --gpg-sign",
            )
            self.assertTrue(decision.branch_has_unique_commits)

    def test_classic_release_opener_commit_can_promote_alpha_to_rc(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.5.0")
            self._git(root, "tag", "1.5.0")
            self._git(root, "checkout", "-b", "develop")
            self._set_version(
                root,
                "1.6.0-alpha.0",
                message="bump: version 1.5.0 -> 1.6.0-alpha.0",
            )
            self._git(root, "checkout", "-b", "release/1.6.0")
            self._commit_empty(root, "chore: open release")

            decision = decide_version_strategy(root, "release/1.6.0", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "promote-alpha-to-rc")
            self.assertEqual(
                decision.args,
                "--yes --increment PATCH --prerelease rc --gpg-sign",
            )

    def test_classic_release_opener_with_github_pr_suffix_can_promote_alpha_to_rc(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.5.0")
            self._git(root, "tag", "1.5.0")
            self._git(root, "checkout", "-b", "develop")
            self._set_version(
                root,
                "1.6.0-alpha.0",
                message="bump: version 1.5.0 -> 1.6.0-alpha.0",
            )
            self._git(root, "checkout", "-b", "release/1.6.0")
            self._commit_empty(root, "chore: open release (#11)")

            decision = decide_version_strategy(root, "release/1.6.0", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "promote-alpha-to-rc")
            self.assertEqual(
                decision.args,
                "--yes --increment PATCH --prerelease rc --gpg-sign",
            )

    def test_start_subject_opens_next_develop_cycle(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.6.0-alpha.3", message="fix: keep shipping alpha work")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "Start 1.7.0")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "develop-start-cycle")
            self.assertEqual(
                decision.args,
                "--yes --increment MINOR --prerelease alpha --increment-mode exact",
            )
            self.assertTrue(decision.create_tag)

    def test_start_subject_with_github_pr_suffix_opens_next_develop_cycle(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "0.1.0", message="fix: keep shipping alpha work")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "Start 0.2.0 (#7)")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "develop-start-cycle")
            self.assertEqual(
                decision.args,
                "--yes --increment MINOR --prerelease alpha --increment-mode exact",
            )
            self.assertTrue(decision.create_tag)

    def test_release_subject_is_rejected_on_develop(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.7.0-alpha.2", message="fix: keep shipping alpha work")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "Release 1.6.0")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertTrue(decision.invalid)
            self.assertIn("reserved for release promotion to master", decision.error)
            self.assertIn("Backmerge Release 1.6.0", decision.error)

    def test_hotfix_subject_is_rejected_on_develop(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.7.0-alpha.2", message="fix: keep shipping alpha work")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "Hotfix 1.6.1")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertTrue(decision.invalid)
            self.assertIn("reserved for hotfix promotion to master", decision.error)
            self.assertIn("Backmerge Hotfix 1.6.1", decision.error)

    def test_release_backmerge_advances_alpha_when_meaningful_changes_land(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.7.0-alpha.2", message="fix: keep shipping alpha work")
            self._git(root, "checkout", "-b", "develop")
            (root / "release-fix.txt").write_text("carry release fix back\n", encoding="utf-8")
            self._commit_all(root, "Backmerge Release 1.6.0")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "develop-backmerge-release")
            self.assertEqual(
                decision.args,
                "--yes --increment PATCH --prerelease alpha --no-tag",
            )
            self.assertFalse(decision.create_tag)

    def test_release_backmerge_with_github_pr_suffix_advances_alpha(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.7.0-alpha.2", message="fix: keep shipping alpha work")
            self._git(root, "checkout", "-b", "develop")
            (root / "release-fix.txt").write_text("carry release fix back\n", encoding="utf-8")
            self._commit_all(root, "Backmerge Release 1.6.0 (#12)")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "develop-backmerge-release")
            self.assertEqual(
                decision.args,
                "--yes --increment PATCH --prerelease alpha --no-tag",
            )
            self.assertFalse(decision.create_tag)

    def test_release_backmerge_catches_stable_develop_up_to_target_when_not_ahead(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.5.0", message="fix: production stabilization")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "Backmerge Release 1.6.0")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "develop-backmerge-release-stable")
            self.assertEqual(
                decision.args,
                "--yes --increment MINOR --increment-mode exact --no-tag",
            )
            self.assertFalse(decision.create_tag)

    def test_release_backmerge_finalizes_rc_on_develop_when_not_ahead(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.6.0-rc.0", message="fix: stabilize release candidate")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "Backmerge Release 1.6.0")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "develop-backmerge-release-stable")
            self.assertEqual(
                decision.args,
                "--yes --no-tag",
            )
            self.assertFalse(decision.create_tag)

    def test_hotfix_backmerge_advances_alpha_when_meaningful_changes_land(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.7.0-alpha.2", message="fix: keep shipping alpha work")
            self._git(root, "checkout", "-b", "develop")
            (root / "hotfix-fix.txt").write_text("carry hotfix back\n", encoding="utf-8")
            self._commit_all(root, "Backmerge Hotfix 1.6.1")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "develop-backmerge-hotfix")
            self.assertEqual(
                decision.args,
                "--yes --increment PATCH --prerelease alpha --no-tag",
            )
            self.assertFalse(decision.create_tag)

    def test_hotfix_backmerge_catches_stable_develop_up_to_patch_when_not_ahead(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.6.0", message="fix: production stabilization")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "Backmerge Hotfix 1.6.1")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "develop-backmerge-hotfix-stable")
            self.assertEqual(
                decision.args,
                "--yes --increment PATCH --increment-mode exact --no-tag",
            )
            self.assertFalse(decision.create_tag)

    def test_hotfix_backmerge_finalizes_rc_on_develop_when_not_ahead(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.6.1-rc.0", message="fix: stabilize hotfix candidate")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "Backmerge Hotfix 1.6.1")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "develop-backmerge-hotfix-stable")
            self.assertEqual(
                decision.args,
                "--yes --no-tag",
            )
            self.assertFalse(decision.create_tag)

    def test_backmerge_can_skip_when_latest_commit_only_touches_version_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.7.0-alpha.2", message="fix: keep shipping alpha work")
            self._git(root, "checkout", "-b", "develop")
            pyproject_path = root / "pyproject.toml"
            pyproject_path.write_text(
                pyproject_path.read_text(encoding="utf-8") + "\n",
                encoding="utf-8",
            )
            self._commit_all(root, "Backmerge Release 1.6.0")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertTrue(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "")
            self.assertIn("introduced no meaningful unique changes", decision.reason)

    def test_backmerge_can_skip_when_stable_develop_already_matches_target(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.6.0", message="fix: production stabilization")
            self._git(root, "checkout", "-b", "develop")
            self._commit_empty(root, "Backmerge Release 1.6.0")

            decision = decide_version_strategy(root, "develop", flow="classic")

            self.assertTrue(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "")
            self.assertIn("already matches stable line 1.6.0", decision.reason)

    def test_develop_resumes_alpha_after_stable_finalize_when_next_commit_is_conventional(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.6.0", message="fix: production stabilization")
            self._git(root, "tag", "1.6.0")
            self._git(root, "checkout", "-b", "develop")
            (root / "next-cycle.txt").write_text("start the next cycle\n", encoding="utf-8")
            self._commit_all(root, "feat: start the next develop cycle")

            decision = decide_version_strategy(root, "develop", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(
                decision.args,
                "--yes --prerelease alpha --default-increment PATCH",
            )
            self.assertTrue(decision.create_tag)


    def test_hotfix_backmerge_prep_with_rc_continues_rc_line(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "0.2.1-rc.0")
            self._git(root, "tag", "0.2.1-rc.0")
            self._git(root, "checkout", "-b", "hotfix/session-fix")
            self._commit_empty(root, "chore: merge develop for backmerge")

            decision = decide_version_strategy(root, "hotfix/session-fix", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "backmerge-prep-rc")
            self.assertEqual(
                decision.args,
                "--yes --increment PATCH --prerelease rc --no-tag",
            )
            self.assertFalse(decision.create_tag)

    def test_hotfix_backmerge_prep_with_alpha_continues_alpha_line(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "0.3.0-alpha.5")
            self._git(root, "tag", "0.3.0-alpha.5")
            self._git(root, "checkout", "-b", "hotfix/session-fix")
            self._commit_empty(root, "chore: merge develop for backmerge")

            decision = decide_version_strategy(root, "hotfix/session-fix", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "backmerge-prep-alpha")
            self.assertEqual(
                decision.args,
                "--yes --prerelease alpha --default-increment PATCH --no-tag",
            )
            self.assertFalse(decision.create_tag)

    def test_release_backmerge_prep_with_rc_continues_rc_line(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            self._init_repo(root, "1.0.0-rc.1")
            self._git(root, "tag", "1.0.0-rc.1")
            self._git(root, "checkout", "-b", "develop")
            self._git(root, "checkout", "-b", "release/1.0.0")
            self._commit_empty(root, "chore: merge develop for backmerge")

            decision = decide_version_strategy(root, "release/1.0.0", flow="variant")

            self.assertFalse(decision.skip)
            self.assertFalse(decision.invalid)
            self.assertEqual(decision.mode, "backmerge-prep-rc")
            self.assertFalse(decision.create_tag)


if __name__ == "__main__":
    unittest.main()
